apiVersion: v1
kind: Service
metadata:
  name: paymentDB
  labels:
    app: paymentDB
    tier: database
spec:
  ports:
    - port: 3307
      targetPort: 3307
  selector:
    app: paymentDB
    tier: database
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentDB-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: paymentDB
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 100Mi    #This will tell kubernetes about the amount of space we are trying to claim.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentDB
  labels:
    app: paymentDB
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: paymentDB
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: paymentDB
        tier: database
    spec:
      containers:
        - name: paymentDB
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: paypal
          ports:
            - containerPort: 3307
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-paymentDB-storage
      volumes:
        - name: mysql-paymentDB-storage
          persistentVolumeClaim:
            claimName: paymentDB-pv-claim
